crowdanki_uuid: 6583283a-ad9d-11ea-8887-f45c89c920a5
deck_config_uuid: b075974b-3d82-43d1-8947-28d8976a023d
deck_configurations:
- __type__: DeckConfig
  autoAgain: 0
  autoAlert: 0
  autoAnswer: 0
  autoplay: false
  crowdanki_uuid: b075974b-3d82-43d1-8947-28d8976a023d
  dyn: false
  interdayLearningMix: 0
  lapse:
    delays:
    - 10.0
    leechAction: 0
    leechFails: 8
    minInt: 1
    mult: 0.0
  maxTaken: 60
  name: Default
  new:
    bury: true
    delays:
    - 1.0
    - 10.0
    initialFactor: 2500
    ints:
    - 1
    - 4
    - 0
    order: 0
    perDay: 15
    separate: true
  newMix: 0
  newPerDayMinimum: 0
  replayq: true
  rev:
    bury: true
    ease4: 1.3
    fuzz: 0.05
    hardFactor: 1.2
    ivlFct: 1.0
    maxIvl: 36500
    minSpace: 1
    perDay: 100
  reviewOrder: 0
  timer: 0
desc: "<a href=\"https://github.com/HartBlanc/anki-uk-geography\"><b>Additional Documentation\
  \ and Feedback</b></a>\n\nThe deck will help you to learn:\n<ul><li><a href=\"https://en.wikipedia.org/wiki/NUTS_statistical_regions_of_the_United_Kingdom\"\
  >12 top level regions</a> (e.g. Scotland, East of England...)</li>\n<li><a href=\"\
  https://en.wikipedia.org/wiki/NUTS_statistical_regions_of_the_United_Kingdom\">32\
  \ Scottish Council Areas</a> and 64 Ceremonial Counties for <a href=\"https://en.wikipedia.org/wiki/Ceremonial_counties_of_England\"\
  >England</a>, <a href=\"https://en.wikipedia.org/wiki/Preserved_counties_of_Wales\"\
  >Wales</a>, and <a href=\"https://en.wikipedia.org/wiki/Counties_of_Northern_Ireland\"\
  >Northern Ireland</a></li>\n<li><a href=\"https://en.wikipedia.org/wiki/List_of_cities_in_the_United_Kingdom\"\
  >69 Official Cities</a></li>\n<li>15 assorted seas, channels, estuaries, straits\
  \ and oceans</li></ul>\n<strong>Deck Features</strong>\n<ul><li>The deck is light-weight\
  \ (~1MB, despite containing ~205 unique images)</li>\n<li>All images are Scalable\
  \ Vector Graphics and therefore scale gracefully to any screen size without distortion</li>\n\
  <li>Colours are distribued across maps to encourage colour-based memory retention</li>\n\
  <li>CSS is used to generate unique images and to animate cards</li></ul>\nThis deck\
  \ is <a href=\"https://github.com/HartBlanc/anki-uk-geography\"><b>maintained on\
  \ GitHub</b></a>.\nFound a bug? Interested in adding new cards or new features?\
  \ <a href=\"https://github.com/HartBlanc/anki-uk-geography/issues\">Raise an issue</a>\n\
  or check out the project documentation on <a href=\"https://github.com/HartBlanc/anki-uk-geography\"\
  >Github</a>."
dyn: 0
extendNew: 1
extendRev: 50
name: United Kingdom Geography - Regions Counties and Cities
